name: splinesoft.net

on:
  push:
    branches: [ "master" ]

jobs:
  build:
     runs-on: ubuntu-latest
     env:
       JEKYLL_ENV: production
     steps:
     - uses: actions/checkout@v3
     - uses: ruby/setup-ruby@v1
       with:
         ruby-version: 3.1.2
     - name: Bundle install
       run: rake setup
     - name: jekyll build
       run: rake build
     - name: Lint
       run: rake lint
     - name: cache
       uses: actions/upload-artifact@v3.1.2
       with:
         name: site
         path: _site
         if-no-files-found: error 
     
  deploy:
      runs-on: ubuntu-latest
      needs: build
      concurrency: production
      steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: s3cmd
        run: |
          python -m pip install --upgrade pip
          pip install s3cmd
          s3cmd --version
      - name: Download site
        uses: actions/download-artifact@v3
        with:
          name: site
          path: _site
      - name: Publish
        env:
          PUSHOVER_APP: ${{ secrets.pushover_app }}
          PUSHOVER_USER: ${{ secrets.pushover_user }}
          SITE_AWS_KEY: ${{ secrets.site_aws_key }}
          SITE_AWS_SECRET: ${{ secrets.site_aws_secret }}
        run: scripts/publish.sh
